---
title: "Antarctic Fish Viromes"
author: "R. M. Grimwood"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Library Imports
```{r Libraries, message=FALSE, warning=FALSE}

library(ggplot2)
library(reshape2)
library(tidyverse)
library(vegan)

```

## Import data and metadata
```{r Data imports}

# Raw abundance data
raw_abun = read.csv("Raw_abundances.csv", header=TRUE)

# Standardised abundance data (RPM)
stand_abun = read.csv("RPM_abundances.csv", header=TRUE)

# Metadata
meta_data = raw_abun[,1:10]

```

## Abundances
```{r Abundances}

# Total sequencing reads
depth = as.data.frame(meta_data[,9])
depth = cbind(raw_abun[,1], depth)
rownames(depth) = depth[,1]

depth = depth [c("MRL_L", "MRL_H", "ANT_L", "ANT_H", "WGR_L", "WGR_H", "QMC_L", "QMC_H", "LVD_L", "LVD_H", "TRD_L", "TRD_H", "TLO_L", "TLO_H", "CHW_L", "CHW_H", "SZT_L", "SZT_H", "PIM_L", "PIM_H", "BVK_L", "BVK_H"),]

depth[,1] = factor(depth[,1], levels = rownames(depth))
colnames(depth) = c("V1", "V2")

ggplot(data=as.data.frame(depth), aes(x=V1, y=V2)) +
  geom_bar(stat="identity") + theme_light() + scale_y_continuous(labels = function(x) format(x, scientific = FALSE))



# Bar plots - RPS13, total virome, vert/fish virome
vert_viruses = rowSums(stand_abun[,11:31]) # Sum vert viruses
vert_viruses = as.matrix(vert_viruses) 
virome_and_RPS13 = cbind(stand_abun[,32], vert_viruses, stand_abun[,10]) # combine vert, total virome, and RPS13
colnames(virome_and_RPS13) = c("Total.virome", "Vert.viruses", "RPS13")
rownames(virome_and_RPS13) = stand_abun[,1]

melted_abun_for_plot = melt(virome_and_RPS13)

ggplot(data=melted_abun_for_plot, aes(x=Var1, y=value, fill=Var2)) +
  geom_bar(stat="identity", position=position_dodge()) + 
  coord_flip() + 
  theme_light() +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_fill_manual(values = c("grey", "black", "dodgerblue3"))



# Only vert and RPS13
virome_and_RPS13 = cbind(vert_viruses, stand_abun[,10]) # combine vert, total virome, and RPS13
colnames(virome_and_RPS13) = c("Vert.viruses", "RPS13")
rownames(virome_and_RPS13) = stand_abun[,1]

melted_abun_for_plot = melt(virome_and_RPS13)

ggplot(data=melted_abun_for_plot, aes(x=Var1, y=value, fill=Var2)) +
  geom_bar(stat="identity", position=position_dodge()) + 
  coord_flip() + 
  theme_light() +
  scale_y_continuous(labels = function(x) format(x, scientific = FALSE)) +
  scale_fill_manual(values = c("grey", "black", "dodgerblue3"))






# Normalised vertebrate viruses (excludes non-vert)
norm_abun_vert = sweep(stand_abun[,11:31],1,rowSums(stand_abun[,11:31]),"/") # normalise by library 
norm_abun_vert = cbind(stand_abun[,1], norm_abun_vert)
rownames(norm_abun_vert) = norm_abun_vert[,1]


# Order names
tree_order = c("MRL_L", "MRL_H", "ANT_L", "ANT_H", "WGR_L", "WGR_H", "QMC_L", "QMC_H", "LVD_L", "LVD_H", "TRD_L", "TRD_H", "TLO_L", "TLO_H", "CHW_L", "CHW_H", "SZT_L", "SZT_H", "PIM_L", "PIM_H", "BVK_L", "BVK_H")
tree_order = rev(tree_order)
norm_abun_vert = norm_abun_vert[tree_order,]
norm_abun_vert[,1] = factor(norm_abun_vert[,1], levels = rownames(norm_abun_vert))

melted_norm_abun_vert = melt(norm_abun_vert)

colnames(melted_norm_abun_vert) = c("Var1", "Var2", "value")

ggplot(data=melted_norm_abun_vert, aes(x=Var1, y=value, fill=Var2)) +
  geom_bar(stat="identity") + coord_flip() + theme_light() + 
  scale_fill_manual(values = c(
  "#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a",
  "#b15928", "#a6cee3", "#b2df8a", "#fb9a99", "#fdbf6f",
  "#cab2d6", "#ffff99", "#c15628", "#8dd3c7", "#fb8072",
  "#80b1d3", "#bebada", "#ffed6f", "#fdb462", "#c0c0c0",
  "#8c564b"))




# Normalised vertebrate viruses by species
merged_raw = read.csv("Raw_abundances_merged.csv", header=TRUE)

norm_merge_abun = sweep(merged_raw[,11:31],1,rowSums(merged_raw[,11:31]),"/") # normalise by library 
norm_merge_abun = cbind(merged_raw[,1], norm_merge_abun)
rownames(norm_merge_abun) = norm_merge_abun[,1]


# Order names
tree_order = c("MRL", "ANT", "WGR", "QMC", "LVD", "TRD", "TLO", "CHW", "SZT", "PIM", "BVK")
tree_order = rev(tree_order)
norm_merge_abun = norm_merge_abun[tree_order,]
norm_merge_abun[,1] = factor(norm_merge_abun[,1], levels = rownames(norm_merge_abun))

melted_norm_merge_abun = melt(norm_merge_abun)

colnames(melted_norm_merge_abun) = c("Var1", "Var2", "value")

ggplot(data=melted_norm_merge_abun, aes(x=Var1, y=value, fill=Var2)) +
  geom_bar(stat="identity") + coord_flip() + theme_light() + 
  scale_fill_manual(values = c(
  "#1f78b4", "#33a02c", "#e31a1c", "#ff7f00", "#6a3d9a",
  "#b15928", "#a6cee3", "#b2df8a", "#fb9a99", "#fdbf6f",
  "#cab2d6", "#ffff99", "#c15628", "#8dd3c7", "#fb8072",
  "#80b1d3", "#bebada", "#ffed6f", "#fdb462", "#c0c0c0",
  "#8c564b"))

```


## Beta diversity
```{r Beta diversity}

# Set seed
set.seed(10)

# NMDS of fish viromes
NMDS_data = stand_abun[,11:31]
rownames(NMDS_data) = stand_abun[,1]
NMDS_data = NMDS_data[-c(2,11,20),]
#NMDS_data_norm = sweep(NMDS_data,1,rowSums(NMDS_data),"/")

# Set up distance matrix - Bray-Curtis distance
vdist = vegdist(NMDS_data, "bray")

# Preform NMDS
nmds = metaMDS(vdist, distance = "bray", trymax = 250, k = 4)
stressplot(nmds)
plot(nmds, type='t', display=c('site', 'species'))

# Extract NMDS with ggplot
nmds_points = as.data.frame(nmds$points)
nmds_points = cbind(nmds_points, stand_abun[-c(2,11,20),c(2,4:5,8)])


# Body mass
adonis2(formula = vdist~Body.mass, data = nmds_points, method = "bray") 

# Order
adonis2(formula = vdist~Order, data = nmds_points, method = "bray")

# Genus
adonis2(formula = vdist~Genus, data = nmds_points, method = "bray")
adonis2(formula = vdist~Genus+Body.mass, data = nmds_points, method = "bray")

# Species
adonis2(formula = vdist~Species, data = nmds_points, method = "bray")

# Plotting
ggplot(nmds_points, aes(x=MDS1, y=MDS2, color=Body.mass)) + geom_point(size = 3, alpha = 0.7) +
  scale_shape(solid = FALSE) +
  labs(title = "NMDS Plot of Vertebrate Family-Level Viromes",
       x = "NMDS Axis 1",
       y = "NMDS Axis 2",
       colour = "Host order") + theme_light() + scale_color_manual(values=c("#AC99C3", "#DB186A", "#F68C28", "#A6D5D6", "#94C066", "#A72E31", "#1E4F5F"))


```


## Network analysis
```{r Network analysis}

# Libraries
library(ergm)
library(ggbipart)
library(ggnet)
library(intergraph)
library(igraph)
library(network)
library(RColorBrewer)
library(sna)

# Network
network = read.csv("Network_abundances.csv", header=TRUE, row.names=1,)

network.net = bip_init_network(network)
network.ig = bip_init_igraph(network)

# RPM-weighted network
bip_ggnet(network.net, as.matrix(network), label = TRUE)

# Railway network
bip_railway(network, label=T)

```

## Arenaviridae plots
```{r Arenaviridae}


# Arenas
arena = data.frame(Library = c("TRD_L", "TLO_L", "MRL_H"), 
                   "RPS13 RPM" = c(40.5697905, 31.5570579, 39.7688602),
                   "Arenaviridae RPM" = c(8.78073778, 221.861847, 7.62185905))

arena_melt = melt(arena)

ggplot(data=arena_melt, aes(x=Library, y=value, fill=variable)) +
  geom_bar(stat="identity", position=position_dodge(width = 1.1)) + 
  theme_light() + 
  scale_fill_manual(values = c("#1f78b4", "#33a02c")) + 
  facet_wrap(~Library, scales = "free_x")

```
